import type { DemoDataset } from "../types";
import type { Opportunity, ActivityEvent } from "@/types/domain";
import {
  minutesBefore,
  hoursBefore,
  daysBefore,
  demoId,
  resetDemoIds,
  seededRandom,
  buildDailyLabel,
} from "../helpers";

export function buildPlumbingDataset(now: Date): DemoDataset {
  const businessId = "biz_riverside_plumbing";
  const businessName = "Riverside Plumbing Co.";
  // Reset before building so the exact same ids come out every time this
  // dataset is (re)built — otherwise a link generated on one page render
  // could point at an id that no longer exists on the next render.
  resetDemoIds(businessId);

  // ---- Opportunities -------------------------------------------------
  const opportunities: Opportunity[] = [
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "missed_call",
      status: "deposit_paid",
      createdAt: minutesBefore(now, 73),
      updatedAt: minutesBefore(now, 60),
      callId: "call_flagship",
      contact: {
        id: demoId(businessId, "contact"),
        businessId,
        name: "Sarah Mitchell",
        phone: "(617) 555-0148",
        email: "sarah.mitchell@example.com",
        isPreviousCustomer: false,
        language: "en",
      },
      messages: [
        { id: demoId(businessId, "msg"), role: "system", channel: "sms", text: "Missed call detected — not identified as spam. Auto text-back sent.", timestamp: minutesBefore(now, 73) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Hi! Sorry we missed your call to Riverside Plumbing Co. How can we help?", timestamp: minutesBefore(now, 72) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Hi, my kitchen sink is draining really slowly and now it smells bad", timestamp: minutesBefore(now, 70) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Got it — sounds like it could use a professional drain cleaning. Is this happening at just the kitchen sink, or other drains too?", timestamp: minutesBefore(now, 69) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Just the kitchen for now", timestamp: minutesBefore(now, 67) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Thanks Sarah! Can I get your service address?", timestamp: minutesBefore(now, 66) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "42 Willow St, Newton", timestamp: minutesBefore(now, 65) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "I have two openings tomorrow: 10:00 AM or 2:00 PM. Which works better?", timestamp: minutesBefore(now, 64) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "2pm works great", timestamp: minutesBefore(now, 62) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "You're booked for tomorrow at 2:00 PM! We ask for a $150 deposit to confirm — here's a secure payment link: pay.example/dep_9f21", timestamp: minutesBefore(now, 61) },
        { id: demoId(businessId, "msg"), role: "system", channel: "sms", text: "$150 deposit paid.", timestamp: minutesBefore(now, 60) },
      ],
      appointment: {
        id: demoId(businessId, "appt"),
        opportunityId: "",
        businessId,
        serviceName: "Kitchen drain cleaning",
        scheduledFor: daysBefore(now, -1, 14, 0),
        status: "scheduled",
        bookedVia: "ai_auto_booked",
      },
      payments: [
        { id: demoId(businessId, "pay"), opportunityId: "", businessId, kind: "deposit", amount: 150, status: "paid", createdAt: minutesBefore(now, 61), paidAt: minutesBefore(now, 60) },
      ],
      confirmedRevenue: 150,
      estimatedValue: 270,
      notes: null,
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "missed_call",
      status: "booked",
      createdAt: hoursBefore(now, 5),
      updatedAt: hoursBefore(now, 4.5),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Carlos Reyes", phone: "(617) 555-0192", email: null, isPreviousCustomer: false, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Hi! Sorry we missed your call to Riverside Plumbing Co. How can we help?", timestamp: hoursBefore(now, 5) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Need a quote to replace my water heater, it's leaking", timestamp: hoursBefore(now, 4.9) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Sorry to hear that! What's your address, and is anyone home during the day for a technician visit?", timestamp: hoursBefore(now, 4.8) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "118 Beacon Ave. Yes, mornings work", timestamp: hoursBefore(now, 4.7) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "I've got Thursday at 9:00 AM open — want me to book that?", timestamp: hoursBefore(now, 4.6) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Yes please", timestamp: hoursBefore(now, 4.5) },
      ],
      appointment: { id: demoId(businessId, "appt"), opportunityId: "", businessId, serviceName: "Water heater replacement", scheduledFor: daysBefore(now, -2, 9, 0), status: "scheduled", bookedVia: "ai_auto_booked" },
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 1800,
      notes: null,
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "web_form",
      status: "qualified",
      createdAt: hoursBefore(now, 20),
      updatedAt: hoursBefore(now, 19),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Emily Chen", phone: "(617) 555-0110", email: "emily.chen@example.com", isPreviousCustomer: false, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "customer", channel: "web", text: "Interested in a full bathroom remodel, plumbing rough-in needed", timestamp: hoursBefore(now, 20) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Thanks for reaching out! A remodel like that usually needs an in-person estimate — what's the best address and a few times that work this week?", timestamp: hoursBefore(now, 19.5) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "204 Maple Dr, I'm around most afternoons", timestamp: hoursBefore(now, 19) },
      ],
      appointment: null,
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 3200,
      notes: "Awaiting staff to confirm in-person estimate time.",
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "missed_call",
      status: "won",
      createdAt: daysBefore(now, 2, 11, 15),
      updatedAt: daysBefore(now, 1, 16, 0),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "James Whitfield", phone: "(617) 555-0173", email: null, isPreviousCustomer: true, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Hi! Sorry we missed your call to Riverside Plumbing Co. How can we help?", timestamp: daysBefore(now, 2, 11, 15) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Pipe burst under the house, need someone NOW", timestamp: daysBefore(now, 2, 11, 16) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "That's an emergency — I'm flagging this for our on-call technician to call you back within 10 minutes.", timestamp: daysBefore(now, 2, 11, 17) },
        { id: demoId(businessId, "msg"), role: "staff", channel: "voice", text: "Technician dispatched same-day. Job completed and invoiced.", timestamp: daysBefore(now, 1, 16, 0) },
      ],
      appointment: { id: demoId(businessId, "appt"), opportunityId: "", businessId, serviceName: "Emergency pipe repair", scheduledFor: daysBefore(now, 2, 13, 0), status: "completed", bookedVia: "staff_booked" },
      payments: [{ id: demoId(businessId, "pay"), opportunityId: "", businessId, kind: "full_payment", amount: 620, status: "paid", createdAt: daysBefore(now, 1, 16, 0), paidAt: daysBefore(now, 1, 16, 5) }],
      confirmedRevenue: 620,
      estimatedValue: 0,
      notes: null,
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "sms",
      status: "escalated_to_human",
      createdAt: hoursBefore(now, 3),
      updatedAt: hoursBefore(now, 2.8),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Priya Patel", phone: "(617) 555-0166", email: "priya.patel@example.com", isPreviousCustomer: false, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "We manage a 24-unit apartment building and need a plumbing service contract — what would that cost?", timestamp: hoursBefore(now, 3) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "That's a great fit for us, but commercial service contracts need a custom quote from our team. I've let them know — someone will follow up shortly!", timestamp: hoursBefore(now, 2.9) },
      ],
      appointment: null,
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 6000,
      notes: "Escalated: outside approved pricing scope (commercial contract).",
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "estimate_follow_up",
      status: "qualified",
      createdAt: daysBefore(now, 6, 10, 0),
      updatedAt: hoursBefore(now, 18),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "David Nguyen", phone: "(617) 555-0121", email: null, isPreviousCustomer: true, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "system", channel: "sms", text: "Estimate for sewer line replacement ($4,200) sent 6 days ago — not yet accepted. Auto follow-up triggered.", timestamp: hoursBefore(now, 18) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Hi David, just checking in on the sewer line estimate we sent over — happy to answer any questions or get you on the schedule.", timestamp: hoursBefore(now, 18) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Still deciding, can you hold the price through end of month?", timestamp: hoursBefore(now, 16) },
      ],
      appointment: null,
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 4200,
      notes: null,
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "previous_customer_reactivation",
      status: "appointment_scheduled",
      createdAt: daysBefore(now, 1, 9, 0),
      updatedAt: hoursBefore(now, 22),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Linda Brooks", phone: "(617) 555-0134", email: "linda.brooks@example.com", isPreviousCustomer: true, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Hi Linda! It's been about a year since your last water heater flush with Riverside Plumbing. Want us to get you back on the schedule?", timestamp: daysBefore(now, 1, 9, 0) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Yes, that would be great", timestamp: daysBefore(now, 1, 9, 20) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "You're set for next Tuesday at 11:00 AM!", timestamp: hoursBefore(now, 22) },
      ],
      appointment: { id: demoId(businessId, "appt"), opportunityId: "", businessId, serviceName: "Annual water heater maintenance", scheduledFor: daysBefore(now, -5, 11, 0), status: "scheduled", bookedVia: "ai_auto_booked" },
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 180,
      notes: null,
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "missed_call",
      status: "lost",
      createdAt: daysBefore(now, 4, 15, 0),
      updatedAt: daysBefore(now, 3, 9, 0),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Tom Alvarez", phone: "(617) 555-0157", email: null, isPreviousCustomer: false, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Hi! Sorry we missed your call to Riverside Plumbing Co. How can we help?", timestamp: daysBefore(now, 4, 15, 0) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Looking for a faucet install quote", timestamp: daysBefore(now, 4, 15, 10) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Went with another company, thanks anyway", timestamp: daysBefore(now, 3, 9, 0) },
      ],
      appointment: null,
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 0,
      notes: "Customer chose a competitor.",
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "answered_call",
      status: "won",
      createdAt: daysBefore(now, 3, 13, 0),
      updatedAt: daysBefore(now, 3, 15, 0),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Grace Kim", phone: "(617) 555-0188", email: null, isPreviousCustomer: false, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "staff", channel: "voice", text: "Call answered live by staff. Garbage disposal install scheduled and completed same day.", timestamp: daysBefore(now, 3, 13, 0) },
      ],
      appointment: { id: demoId(businessId, "appt"), opportunityId: "", businessId, serviceName: "Garbage disposal install", scheduledFor: daysBefore(now, 3, 14, 0), status: "completed", bookedVia: "staff_booked" },
      payments: [{ id: demoId(businessId, "pay"), opportunityId: "", businessId, kind: "full_payment", amount: 310, status: "paid", createdAt: daysBefore(now, 3, 15, 0), paidAt: daysBefore(now, 3, 15, 0) }],
      confirmedRevenue: 310,
      estimatedValue: 0,
      notes: null,
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "missed_call",
      status: "ai_responding",
      createdAt: minutesBefore(now, 6),
      updatedAt: minutesBefore(now, 2),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Robert Diaz", phone: "(617) 555-0142", email: null, isPreviousCustomer: false, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Hi! Sorry we missed your call to Riverside Plumbing Co. How can we help?", timestamp: minutesBefore(now, 6) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Garbage disposal is leaking under the sink", timestamp: minutesBefore(now, 4) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "Got it — what's your address, and is today or tomorrow better for a visit?", timestamp: minutesBefore(now, 2) },
      ],
      appointment: null,
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 240,
      notes: null,
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "web_form",
      status: "new",
      createdAt: minutesBefore(now, 1),
      updatedAt: minutesBefore(now, 1),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Angela Foster", phone: "(617) 555-0199", email: "angela.foster@example.com", isPreviousCustomer: false, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "customer", channel: "web", text: "Do you install tankless water heaters?", timestamp: minutesBefore(now, 1) },
      ],
      appointment: null,
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 0,
      notes: null,
    },
    {
      id: demoId(businessId, "opp"),
      businessId,
      source: "sms",
      status: "booked",
      createdAt: daysBefore(now, 1, 17, 0),
      updatedAt: hoursBefore(now, 10),
      callId: null,
      contact: { id: demoId(businessId, "contact"), businessId, name: "Marcus Webb", phone: "(617) 555-0177", email: null, isPreviousCustomer: false, language: "en" },
      messages: [
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Need an outdoor spigot installed before winter", timestamp: daysBefore(now, 1, 17, 0) },
        { id: demoId(businessId, "msg"), role: "ai", channel: "sms", text: "We can help! I've got Friday at 1:00 PM open — want that slot?", timestamp: daysBefore(now, 1, 17, 20) },
        { id: demoId(businessId, "msg"), role: "customer", channel: "sms", text: "Works for me", timestamp: hoursBefore(now, 10) },
      ],
      appointment: { id: demoId(businessId, "appt"), opportunityId: "", businessId, serviceName: "Outdoor spigot install", scheduledFor: daysBefore(now, -3, 13, 0), status: "scheduled", bookedVia: "ai_auto_booked" },
      payments: [],
      confirmedRevenue: 0,
      estimatedValue: 220,
      notes: null,
    },
  ];

  // ---- Recent activity feed ------------------------------------------
  const activity: ActivityEvent[] = [
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[0].id, type: "call_missed", timestamp: minutesBefore(now, 73), summary: "Missed call received from (617) 555-0148" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[0].id, type: "ai_conversation_started", timestamp: minutesBefore(now, 72), summary: "AI conversation started" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[0].id, type: "appointment_booked", timestamp: minutesBefore(now, 62), summary: "Appointment booked — kitchen drain cleaning" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[0].id, type: "deposit_link_sent", timestamp: minutesBefore(now, 61), summary: "Deposit link sent ($150)" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[0].id, type: "payment_received", timestamp: minutesBefore(now, 60), summary: "$150 deposit paid", amount: 150 },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[9].id, type: "call_missed", timestamp: minutesBefore(now, 6), summary: "Missed call received from (617) 555-0142" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[9].id, type: "ai_conversation_started", timestamp: minutesBefore(now, 6), summary: "AI conversation started" },
    { id: demoId(businessId, "act"), businessId, opportunityId: null, type: "spam_blocked", timestamp: minutesBefore(now, 40), summary: "Spam call blocked from (800) 555-0100" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[10].id, type: "customer_replied", timestamp: minutesBefore(now, 1), summary: "New web inquiry from Angela Foster" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[1].id, type: "appointment_booked", timestamp: hoursBefore(now, 4.5), summary: "Appointment booked — water heater replacement" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[4].id, type: "escalated_to_human", timestamp: hoursBefore(now, 2.9), summary: "Conversation escalated to staff — commercial pricing request" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[5].id, type: "estimate_follow_up_sent", timestamp: hoursBefore(now, 18), summary: "Estimate follow-up sent to David Nguyen ($4,200)" },
    { id: demoId(businessId, "act"), businessId, opportunityId: null, type: "spam_blocked", timestamp: hoursBefore(now, 7), summary: "Spam call blocked from (888) 555-0111" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[6].id, type: "previous_customer_reactivated", timestamp: daysBefore(now, 1, 9, 0), summary: "Reactivation message sent to Linda Brooks" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[6].id, type: "appointment_booked", timestamp: hoursBefore(now, 22), summary: "Appointment booked — annual maintenance" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[11].id, type: "appointment_booked", timestamp: hoursBefore(now, 10), summary: "Appointment booked — outdoor spigot install" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[8].id, type: "payment_received", timestamp: daysBefore(now, 3, 15, 0), summary: "$310 payment received — Grace Kim", amount: 310 },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[3].id, type: "payment_received", timestamp: daysBefore(now, 1, 16, 5), summary: "$620 payment received — James Whitfield", amount: 620 },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[3].id, type: "review_requested", timestamp: daysBefore(now, 1, 16, 30), summary: "Review request sent to James Whitfield" },
    { id: demoId(businessId, "act"), businessId, opportunityId: null, type: "review_completed", timestamp: daysBefore(now, 1, 20, 0), summary: "New 5-star Google review received" },
    { id: demoId(businessId, "act"), businessId, opportunityId: null, type: "invoice_reminder_sent", timestamp: daysBefore(now, 2, 8, 0), summary: "Invoice reminder sent — Bayview Condos ($1,050 overdue)" },
    { id: demoId(businessId, "act"), businessId, opportunityId: opportunities[7].id, type: "call_missed", timestamp: daysBefore(now, 4, 15, 0), summary: "Missed call received from (617) 555-0157" },
  ];
  activity.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

  // ---- 14-day trend series -------------------------------------------
  const rand = seededRandom(42);
  const dailySeries = Array.from({ length: 14 }).map((_, i) => {
    const daysAgo = 13 - i;
    const weekday = new Date(now.getTime() - daysAgo * 86_400_000).getDay();
    const weekendDip = weekday === 0 || weekday === 6 ? 0.5 : 1;
    return {
      date: buildDailyLabel(now, daysAgo),
      revenueRecovered: Math.round(rand() * 900 * weekendDip + 150),
      potentialRevenue: Math.round(rand() * 700 * weekendDip + 100),
      callsReceived: Math.round(rand() * 10 * weekendDip + 6),
      callsRecovered: Math.round(rand() * 6 * weekendDip + 2),
      spamBlocked: Math.round(rand() * 6 * weekendDip + 1),
    };
  });

  return {
    businessId,
    businessName,
    industryId: "plumbing",
    planId: "business",
    metrics: {
      revenueRecovered: 12450,
      potentialRevenue: 9300,
      missedCallsRecovered: 47,
      appointmentsBooked: 22,
      estimatesRecovered: 6,
      previousCustomersReactivated: 9,
      overdueInvoicesCollected: 2150,
      spamCallsBlocked: 63,
      reviewsGenerated: 14,
      trends: {
        revenueRecovered: 18,
        potentialRevenue: 14,
        missedCallsRecovered: 12,
        appointmentsBooked: 9,
        estimatesRecovered: 10,
        previousCustomersReactivated: 30,
        overdueInvoicesCollected: -5,
        spamCallsBlocked: 5,
        reviewsGenerated: 22,
      },
    },
    dailySeries,
    activity,
    opportunities,
  };
}
